[package]
name = "bop"
version = "0.1.5"
edition = "2021"

[dependencies]
cliconf = "0.3.0"
dirs = "6.0.0"
rand = "0.9.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
term_size = "0.3.2"
